### ISSUE TITLE
Dont work with axios

### ISSUE THREAD

**Issue by imojiz** [93gaurav93/v-owl-carousel#16]
when I read data with axios and with v-fore between <carousel>, not working. Please guide me to do right. 
Thanks .

**Comment by mayur19** [comment]
I think v-owl-carousel component is initializing before data is added to the component using axios. This is most common problem in most of third party wrappers. In which state or position you are initializing v-owl-carousel ?

**Comment by imojiz** [comment]
My code is like this

`<template>
    <div>
        
<VOwlCarousel>
    <img v-for="image in images" :key="p.id" :src="image.url">


</VOwlCarousel>
        <owl>

        </owl>
    </div>
</template>

<script>
    import axios from 'axios'
    import VOwlCarousel from "vue-owl-carousel/src/Carousel";
    export default {
        name: "specials",
        components: {VOwlCarousel},

        data(){
            return{
                image:[]
            }
        },
        
        created(){
            axios.get('/photos')
                .then((res)=>{
                    this.image.push(res.data)
                })
            console.log(this.pp)
        }
    }
</script>


`

**Comment by imojiz** [comment]
My code is like this 

> <template>
    <div>
        <VOwlCarousel>
            <img v-for="image in images" :key="p.id" :src="image.url">
        </VOwlCarousel>
    </div>
</template>

> <script>
    import axios from "axios"
    import VOwlCarousel from "vue-owl-carousel/src/Carousel";
    export default {
        name: "specials",
        components: {VOwlCarousel},
        data(){
            return{
                image:[]
            }
        },
        created(){
            axios.get("/photos")
                .then((res)=>{
                    this.image.push(res.data)
                })
            console.log(this.image)
        }
    }
</script>

`
![vue](https://user-images.githubusercontent.com/12109262/51422843-59c67480-1bcb-11e9-918d-ceba9ede32f3.JPG)
`

**Comment by imojiz** [comment]
My code is like this

> <template>
    <div>
        <Carousel>
            <img v-for="image in images" :key="p.id" :src="image.url">
        </Carousel>
    </div>
</template>

> <script>
    import axios from "axios"
    import Carousel from "Carousel";
    export default {
        name: "specials",
        components: {Carousel},
        data(){
            return{
                image:[]
            }
        },
        created(){
            axios.get("/photos")
                .then((res)=>{
                    this.image.push(res.data)
                })
            console.log(this.image)
        }
    }
</script>

**Comment by imojiz** [comment]
How I can initializing  v-owl-carousel component after add data to the component using axios?

**Comment by mayur19** [comment]
Try to execute server call in mounted() so when data is received from the component will update. So the code should be something like this 
```
import axios from "axios";
import axios from "axios";`

import carousel from "v-owl-carousel";
export default {
    name: "specials",
    components: {carousel},
    data(){
        return{
            image:[]
        }
    },
    mounted(){
        this.getImagesFromServer();
    },
    methods : {
        getImagesFromServer(){
            axios.get("/photos")
            .then((res)=>{
                this.image.push(res.data)
            })
            console.log(this.image)
        }
      }
  }
```
Actually I followed this workaround for Jquery. Lets see what happens with this wrapper.

**Comment by imojiz** [comment]
@mayur19 thank you very much. your solution is right. but for working Carousel I changed 'mounted' to 'updated' in  v-owl-carousel/src/Carousel.vue code in line 90.

**Comment by vstruhar** [comment]
Not sure how this is a solution, since `mounted` comes after `created` in the vue component [lifecycle](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram).

The thing that worked for me was wrapping carousel component into a div and hiding it with v-if until the data is loaded. [This works because](https://vuejs.org/v2/guide/conditional.html#v-if):
>  The block will only be rendered if the directive’s expression returns a truthy value.

**Sample**
`<template>
    <div v-if="products.length > 0">
        <carousel :items="4">
            <img v-for="product in products" :src="product.imageUrl">
        </carousel>
    </div>
</template>`

`<script>
    import carousel from 'v-owl-carousel';

    export default {
        components: {carousel},
        data() {
            return {
                products: [],
            };
        },
        mounted() {
            this.$http.get('/api/products')
                .then(resp => {
                   this.products = resp.data;
                });
        },
    }
</script>`

**Comment by imojiz** [comment]
@vstruhar ooh yes.it worked. thank you very much.
